// <auto-generated />
using System;
using Aliquota.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aliquota.Infra.Data.Migrations
{
    [DbContext(typeof(AliquotaContext))]
    [Migration("20210127204816_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Aliquota.Domain.Models.Conta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnName("ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DtAplicacao")
                        .HasColumnName("dtAplicacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtResgate")
                        .HasColumnName("dtResgate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("nome")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("ValorAplicacao")
                        .HasColumnName("valorAplicacao")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ValorCorrente")
                        .HasColumnName("valorCorrente")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ValorResgate")
                        .HasColumnName("valorResgate")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("conta");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e83e8294-5c31-4a27-b0bc-14c881ab13b8"),
                            Ativo = true,
                            DtAplicacao = new DateTime(2017, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Marcelo Pereira",
                            ValorAplicacao = 400.00m,
                            ValorCorrente = 1200.00m,
                            ValorResgate = 1020.00000m
                        },
                        new
                        {
                            Id = new Guid("5ca4b1bc-1a3b-4838-8389-734b465a6552"),
                            Ativo = true,
                            DtAplicacao = new DateTime(2017, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Nayra Gomes",
                            ValorAplicacao = 700.00m,
                            ValorCorrente = 2100.00m,
                            ValorResgate = 1785.00000m
                        },
                        new
                        {
                            Id = new Guid("5d3ed0c9-7718-4327-81bd-12762f4bc73c"),
                            Ativo = true,
                            DtAplicacao = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Daniele Ramos",
                            ValorAplicacao = 600.00m,
                            ValorCorrente = 1800.00m,
                            ValorResgate = 1530.00000m
                        },
                        new
                        {
                            Id = new Guid("bc1c6480-d33c-4357-ac04-7857c86021c1"),
                            Ativo = true,
                            DtAplicacao = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Anderson Silva",
                            ValorAplicacao = 200.00m,
                            ValorCorrente = 600.00m,
                            ValorResgate = 510.00000m
                        },
                        new
                        {
                            Id = new Guid("5178c0cd-c66e-4b95-80fb-0c8b3693ea5d"),
                            Ativo = true,
                            DtAplicacao = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Mariana Santos",
                            ValorAplicacao = 800.00m,
                            ValorCorrente = 2400.00m,
                            ValorResgate = 2040.00000m
                        },
                        new
                        {
                            Id = new Guid("754ef93a-05f8-45ab-b014-6fedbd7f051c"),
                            Ativo = true,
                            DtAplicacao = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "José Henrique",
                            ValorAplicacao = 900.00m,
                            ValorCorrente = 2700.00m,
                            ValorResgate = 2295.00000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
