// <auto-generated />
using System;
using Aliquota.Domain.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aliquota.Domain.Migrations
{
    [DbContext(typeof(ClienteContexto))]
    [Migration("20210111135836_initDatabase")]
    partial class initDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Aliquota.Domain.Model.Cliente", b =>
                {
                    b.Property<int>("Id_cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Data_investimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome_cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Valor_investido")
                        .HasColumnType("float");

                    b.HasKey("Id_cliente");

                    b.ToTable("clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
