// <auto-generated />
using System;
using Aliquiota.Infra.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aliquiota.Infra.Migrations
{
    [DbContext(typeof(EFContext))]
    [Migration("20200730003039_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113");

            modelBuilder.Entity("Aliquota.Domain.Aplicacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataRegistro");

                    b.Property<DateTime?>("DataResgate");

                    b.Property<double>("RentabilidadeDiaria");

                    b.Property<int>("UsuarioId");

                    b.Property<double>("ValorAplicado");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Aplicacoes");
                });

            modelBuilder.Entity("Aliquota.Domain.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Aliquota.Domain.Aplicacao", b =>
                {
                    b.HasOne("Aliquota.Domain.Usuario")
                        .WithMany("Aplicacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
