// <auto-generated />
using System;
using Aliquota.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aliquota.Migrations
{
    [DbContext(typeof(MyDatabaseContext))]
    [Migration("20210411021557_seed")]
    partial class seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Aliquota.Models.Aplicacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("dataAplicacao")
                        .HasColumnType("datetime2");

                    b.Property<double>("valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Aplicacao");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            dataAplicacao = new DateTime(1999, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            valor = 2000.0
                        },
                        new
                        {
                            Id = 3,
                            dataAplicacao = new DateTime(1999, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            valor = 3000.0
                        });
                });

            modelBuilder.Entity("Aliquota.Models.IR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("aliquota")
                        .HasColumnType("float");

                    b.Property<DateTime>("dataAplicacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dataResgate")
                        .HasColumnType("datetime2");

                    b.Property<double>("ir")
                        .HasColumnType("float");

                    b.Property<double>("lucro")
                        .HasColumnType("float");

                    b.Property<double>("valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("IR");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            aliquota = 0.14999999999999999,
                            dataAplicacao = new DateTime(1999, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dataResgate = new DateTime(2021, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ir = 290.39999999999998,
                            lucro = 1936.0,
                            valor = 1000.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
