// <auto-generated />
using Aliquota.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aliquota.Migrations
{
    [DbContext(typeof(MyDatabaseContext))]
    partial class MyDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Aliquota.Models.Aplicacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("dataAplicacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Aplicacao");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            dataAplicacao = "19/09/1999",
                            valor = 2000.0
                        },
                        new
                        {
                            Id = 3,
                            dataAplicacao = "17/04/1987",
                            valor = 3000.0
                        });
                });

            modelBuilder.Entity("Aliquota.Models.IR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("aliquota")
                        .HasColumnType("float");

                    b.Property<string>("dataAplicacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dataResgate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ir")
                        .HasColumnType("float");

                    b.Property<double>("lucro")
                        .HasColumnType("float");

                    b.Property<double>("valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("IR");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            aliquota = 0.14999999999999999,
                            dataAplicacao = "19/09/1999",
                            dataResgate = "22/12/2021",
                            ir = 290.39999999999998,
                            lucro = 1936.0,
                            valor = 1000.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
