// <auto-generated />
using Aliquota.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aliquota.Migrations
{
    [DbContext(typeof(MyDatabaseContext))]
    partial class MyDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Aliquota.Models.Aplicacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("dataAplicacao")
                        .HasColumnName("dataAplicacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("valor")
                        .HasColumnName("valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Aplicacao");
                });

            modelBuilder.Entity("Aliquota.Models.IR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("aliquota")
                        .HasColumnName("aliquota")
                        .HasColumnType("float");

                    b.Property<string>("dataAplicacao")
                        .HasColumnName("dataAplicacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dataResgate")
                        .HasColumnName("dataResgate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ir")
                        .HasColumnName("ir")
                        .HasColumnType("float");

                    b.Property<double>("lucro")
                        .HasColumnName("lucro")
                        .HasColumnType("float");

                    b.Property<double>("valor")
                        .HasColumnName("valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("IR");
                });
#pragma warning restore 612, 618
        }
    }
}
