// <auto-generated />
using System;
using Aliquota.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aliquota.Domain.Migrations
{
    [DbContext(typeof(AliquotaContext))]
    [Migration("20210410174533_ModificacaoAdicaoCampos")]
    partial class ModificacaoAdicaoCampos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Aliquota.Domain.Models.Aplicacoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<double>("Rentabilidade_Mes")
                        .HasColumnType("REAL");

                    b.Property<bool>("Resgatada")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Aplicacoes");
                });

            modelBuilder.Entity("Aliquota.Domain.Models.Historicos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AplicacaoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<double>("Lucro")
                        .HasColumnType("REAL");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AplicacaoId");

                    b.ToTable("Historicos");
                });

            modelBuilder.Entity("Aliquota.Domain.Models.Resgates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AplicacaoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<double>("Lucro")
                        .HasColumnType("REAL");

                    b.Property<double>("Valor_IR")
                        .HasColumnType("REAL");

                    b.Property<double>("Valor_Retirado")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AplicacaoId");

                    b.ToTable("Resgates");
                });

            modelBuilder.Entity("Aliquota.Domain.Models.Historicos", b =>
                {
                    b.HasOne("Aliquota.Domain.Models.Aplicacoes", "Aplicacoes")
                        .WithMany("Hisotricos")
                        .HasForeignKey("AplicacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aplicacoes");
                });

            modelBuilder.Entity("Aliquota.Domain.Models.Resgates", b =>
                {
                    b.HasOne("Aliquota.Domain.Models.Aplicacoes", "Aplicacao")
                        .WithMany()
                        .HasForeignKey("AplicacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aplicacao");
                });

            modelBuilder.Entity("Aliquota.Domain.Models.Aplicacoes", b =>
                {
                    b.Navigation("Hisotricos");
                });
#pragma warning restore 612, 618
        }
    }
}
