// <auto-generated />
using System;
using Aliquota.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aliquota.Domain.Migrations
{
    [DbContext(typeof(InvestimentoContext))]
    [Migration("20210922130600_Criar")]
    partial class Criar
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("Aliquota.Domain.Models.Investimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataDeInicio")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataDeResgate")
                        .HasColumnType("datetime");

                    b.Property<double>("Lucro")
                        .HasColumnType("double");

                    b.Property<int>("TempoEmAnos")
                        .HasColumnType("int");

                    b.Property<int>("TempoEmDias")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Investimentos");
                });
#pragma warning restore 612, 618
        }
    }
}
