// <auto-generated />
using System;
using Aliquota.Domain.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aliquota.Domain.Migrations
{
    [DbContext(typeof(AplicacaoContext))]
    partial class AplicacaoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("Aliquota.Domain.Models.AplicacaoModel", b =>
                {
                    b.Property<int>("AplicacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAplicada")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataRetirada")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ValorFinalBruto")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ValorImpostoRenda")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorInicial")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ValorLucroLiquido")
                        .HasColumnType("TEXT");

                    b.HasKey("AplicacaoId");

                    b.ToTable("Aplicacao");
                });
#pragma warning restore 612, 618
        }
    }
}
