// <auto-generated />
using System;
using Aliquota.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aliquota.Infra.Data.Migrations
{
    [DbContext(typeof(AliquotaContext))]
    partial class AliquotaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("Aliquota.Domain.Entities.AplicacaoFinanceira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAplicacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataResgate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RentabilidadeAnual")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorAplicacao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AplicacaoFinanceira");
                });
#pragma warning restore 612, 618
        }
    }
}
