CREATE TABLE [dbo].[ProdutoFinanceiro](
	[ID] [INT] NOT NULL,
	[Descricao] [VARCHAR] (255) NOT NULL,
	[Rendimento] [DECIMAL] (5,2) NOT NULL,
	[Custo] DECIMAL(12, 2) NOT NULL, 
 CONSTRAINT [PK_ProdutoFinanceiro] PRIMARY KEY CLUSTERED ([ID] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO


