CREATE TABLE [dbo].[Cliente](
	[ID] [INT] NOT NULL,
	[Nome] [VARCHAR] (255) NOT NULL,
 CONSTRAINT [PK_Cliente] PRIMARY KEY CLUSTERED ([ID] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
GO


